<?php
$listarray = array ( array ( 'label' => 'Bezeichnung',
                             'name' => 'bez', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldBez' ),
                     array ( 'label' => 'Name',
                             'name' => 'name', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldName' ),
                     array ( 'label' => 'PHP-Code',
                             'name' => 'phpcode', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldphp' ),
                     array ( 'label' => 'Menu-ID',
                             'name' => 'menuid', 
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldMenuID' ),
                     array ( 'label' => 'Target',
                             'name' => 'target', 
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldTarget' ),
                     array ( 'label' => 'Parameter',
                             'name' => 'param', 
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldParam' ),
                     array ( 'label' => 'Typ',
                             'name' => 'typ', 
                             'width' => 20, 
                             'type' => 'text',
                             'dbfield' => 'fldTyp' ),
                     array ( 'label' => 'Aktiv',
                             'name' => 'aktiv', 
                             'width' => 20, 
                             'type' => 'JN',
                             'dbfield' => 'fldaktiv' ));

//$filterarray = array ( array ( 'label' => 'Parent',
//                             'name' => 'parent', 
//                             'width' => 10, 
//                             'type' => 'selectid',
//                             'sign' => '=',
//                             'dbtable' => 'tblmenu_liste',
//                             'seldbfield' => 'fldbez',
//                             'seldbindex' => 'fldindex',
//                             'dbfield' => 'fldMenuID' ));

$pararray = array ( 'headline' => 'Funktionen ',
                    'dbtable' => 'tblfunc',
                    'orderby' => 'fldName',
                    'strwhere' => '',
                    'fldindex' => 'fldindex');
?>