<?php
$listarray = array ( array ( 'label' => 'Von Datenbank',
                             'name' => 'vondbase',
                             'width' => 20, 
                             'type' => 'selectid',
                             'dbtable' => 'tbldatabase',
                             'seldbfield' => 'fldbemerk',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_vondatabase' ),
                     array ( 'label' => 'Tablename',
                             'name' => 'dbtblname', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'flddbtblname' ),
                     array ( 'label' => 'Indexname',
                             'name' => 'dbtblindex', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'flddbtblindex' ),
                     array ( 'label' => 'Bezeichnung',
                             'name' => 'dbtblbez', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'flddbtblbez' ),
                     array ( 'label' => 'Von Typ',
                             'name' => 'vontyp', 
                             'width' => 100, 
                             'type' => 'selectref',
                             'dbtable' => 'tbldatabase',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'reftable' => 'tblselect',
                             'fldrefindex' => 'fldindex',
                             'dbrefindex' => 'fldid_select',
							        'fldindex' => 'fldindex', 
							        'dbindex' => 'fldid_vondatabase',
                             'dbfield' => 'fldbez' ),
                     array ( 'label' => 'Nach Datenbank',
                             'name' => 'nachdbase',
                             'width' => 20, 
                             'type' => 'selectid',
                             'dbtable' => 'tbldatabase',
                             'seldbfield' => 'fldbemerk',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_nachdatabase' ),
                     array ( 'label' => 'Nach Typ',
                             'name' => 'nachtyp', 
                             'width' => 100, 
                             'type' => 'selectref',
                             'dbtable' => 'tbldatabase',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'reftable' => 'tblselect',
                             'fldrefindex' => 'fldindex',
                             'dbrefindex' => 'fldid_select',
							        'fldindex' => 'fldindex', 
							        'dbindex' => 'fldid_nachdatabase',
                             'dbfield' => 'fldbez' ),
                     array ( 'label' => 'Aktiv',
                             'name' => 'aktiv', 
                             'width' => 10, 
                             'type' => 'JN',
                             'dbfield' => 'fldaktiv' ),
                     array ( 'label' => 'JN',
                             'width' => 5, 
                             'type' => 'icon',
                             'func' => 'mark.php',
                             'dbfield' => 'icon-book' ));


$filterarray = array ( 
                       array ( 'label' => 'von DB:',
                               'name' => 'vondb', 
                               'width' => 10, 
                               'type' => 'selectid',
                               'sign' => '=',
                               'dbtable' => 'tbldatabase',
                               'seldbindex' => 'fldindex',
                               'seldbfield' => 'fldbemerk',
                               'dbfield' => 'fldid_vondatabase' ),
                       array ( 'label' => 'nach DB:',
                               'name' => 'nachdb', 
                               'width' => 10, 
                               'type' => 'selectid',
                               'sign' => '=',
                               'dbtable' => 'tbldatabase',
                               'seldbindex' => 'fldindex',
                               'seldbfield' => 'fldbemerk',
                               'dbfield' => 'fldid_nachdatabase' ));
                               

                             

$pararray = array ( 'headline' => 'Tables',
                    'dbtable' => 'tbltable',
                    'orderby' => 'fldid_vondatabase,flddbtblname',
                    'strwhere' => '',
                    'fldindex' => 'fldindex');
?>